# Generated by Django 4.1.3 on 2022-11-21 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlets',
            fields=[
                ('outlet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outlet_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('logo', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_quatity', models.IntegerField(default=0)),
                ('image', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('outlet_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.outlets')),
            ],
        ),
    ]
