# Generated by Django 4.1.3 on 2022-11-22 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_products_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlets',
            name='owner_id',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
