# Generated by Django 4.1.3 on 2022-11-22 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_outlets_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='list',
            new_name='product_list',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_type',
            field=models.CharField(choices=[('O', 'Online'), ('C', 'Cash On Delivery')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='product_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), default=(12, 23), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('D', 'Delivered'), ('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
