# Generated by Django 4.1.3 on 2022-11-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_list_orders_product_list_orders_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
